Update argon-status.py
This fixes an index out of range exception caused by an empty array of values.


ERROR MESSAGE WAS:
###############################
#> argon-status
Storage Temperature:
Traceback (most recent call last):
  File "/usr/bin/argon-status", line 441, in <module>
    main()
  File "/usr/bin/argon-status", line 393, in main
    show_all( show_devices_list )
  File "/usr/bin/argon-status", line 264, in show_all
    printOutput(result)
  File "/usr/bin/argon-status", line 78, in printOutput
    printTable(data)
  File "/usr/bin/argon-status", line 61, in printTable
    for _key, item in values[0].items():
IndexError: list index out of range